on:
  pull_request:
    types: [closed]
    branches:
      - olm-v*

jobs:
  operator-courier-validate:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged

    steps:
      - name: "Validate the OLM bundle"
        run: "echo operator-courier validate"
      - name: "Get version string"
        run: "echo get version string"
      - name: "Push operator bundle to quay"
        run: "echo push operator-courier-bundle to quay"

